from django.conf.urls import url, include
from rest_framework_mongoengine import routers
from restaurantes import views
from restaurantes import serializers

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'restaurants', serializers.restaurantsViewSet, r"restaurants")

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^listar/$', views.listar, name='listar'),
    url(r'^add/$', views.add, name='add'),
    url(r'^buscar/$', views.buscar, name='buscar'),
    url(r'^archivo/$', views.archivo, name='archivo'),
    url(r'^texto/$', views.texto, name='texto'),
    url(r'^restaurante/(?P<id>[0-9]+)$', views.restaurante, name='restaurante'),
    url(r'^detalles/$', views.detalles, name='detalles'),
    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),
]
